name = "pic-cache"
main = "src/index.ts"
compatibility_date = "2022-08-09"

#route = "https://news.narutos.top/piccache"
# 您也可以删除 行route，它将改用*.workers.dev。

[vars]
FALLBACK_FIGURE = "https://http.cat/404.jpg"

# Secrets
APITOKEN = "v9bc3ybzjaa8wvz5fmffzappx327ksuw"
