name = "pic-cache"
main = "src/index.ts"
compatibility_date = "2022-08-09"

route = "https://news.narutos.top/piccache"

[vars]
FALLBACK_FIGURE = "${FALLBACK_FIGURE}"

# Secrets
# APITOKEN = "<YOUR APITOKEN>"
