name = "pic-cache"
main = "src/index.ts"
compatibility_date = "2022-08-09"

route = "https://news.narutos.top/piccache"

[vars]
FALLBACK_FIGURE = "https://http.cat/404.jpg"

# Secrets
# APITOKEN = "<YOUR APITOKEN>"
