name: Deploy to Cloudflare

on:
  push:
    tags: [ 'v*' ]
#  watch: # 3.手动点击收藏
#    types: [started]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure wrangler.toml
        uses: danielr1996/envsubst-action@1.1.0
        env:
            ROUTE: ${{ secrets.ICW_ROUTE }}
            FALLBACK_FIGURE: ${{ secrets.ICW_FALLBACK_FIGURE }}
        with:
          input: wrangler.toml
          output: wrangler.toml
          
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: | 
            APITOKEN
        env:
          APITOKEN: ${{ secrets.ICW_APITOKEN }}
